contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #metaboigniter channel"
    url: https://nfcore.slack.com/channels/metaboigniter
    about: Discussion about the nf-core/metaboigniter pipeline
